name: CI With Java via Docker

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Copy Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t make-your-choice:test .

      - name: Run tests inside Docker
        env:
          SPRING_PROFILES_ACTIVE: test
        run: |
          docker run --rm make-your-choice:test \
          mvn -Dtest=com.make_your_choice.presentation.controllers.*Test,com.make_your_choice.presentation.controllers.*IntegrationTest test
